/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_htop
#define HEADER_htop
/*
htop - htop.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

//#link m

#define COPYRIGHT "(C) 2004-2012 2014 Hisham Muhammad"

extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
};

extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
#if (HAVE_LIBHWLOC || HAVE_NATIVE_AFFINITY)
extern      { .key;
#endif
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
extern      { .key;
};

typedef bool(*ForeachProcessFn)(Process*, size_t);

int main(int argc, char** argv);

#endif
